### ISSUE TITLE
Text color doesn't change 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/personas-plus#100]
Submitting issue on behalf of Madonna. 

When a user goes to Custom > Apply Custom Theme, they are not able to change the text color of the theme. 

I had difficulties changing text color and wanted to see if we were missing anything or if this is a bug. :)

**Comment by wagnerand** [comment]
This works just fine for me.


<img width="1273" alt="a" src="https://user-images.githubusercontent.com/873258/33090334-e18f7e78-cef3-11e7-86e4-2aa4888d0425.png">

**Comment by caitmuenster** [comment]
MaDonna also wrote back and said it works for her now, too. (Obviously I am challenged. :) )
