### ISSUE TITLE
Personas rotation is not available in version 2.0.0 although advertised

### ISSUE THREAD

**Issue by nturcot** [mozilla/personas-plus#102]
Hello,

Personas Plus AMO page advertises "the ability for Personas Plus to automatically rotate your themes". I could however not find this possibility in 2.0.0 version. Should it be implemented in the Webextension version and/or the description on AMO updated?

The question follows a request [on the French support forums](https://forums.mozfr.org/viewtopic.php?f=5&t=135707) mentioning that Personas Rotator and Personas Switcher no longer work in Firefox 57.

**Comment by wagnerand** [comment]
Thank you for the report!

You are right, I forgot the remove that. The description is updated now. We might want to bring back back functionality, if there is interest.
