### ISSUE TITLE
Theme defaults to firefox

### ISSUE THREAD

**Issue by ukmerlin** [mozilla/personas-plus#103]
I thought this problem was that when Firefox was started it would lose the theme selected and revert to one of the defaults but it turns out that during browsing and moving between tabs the theme will drop out.
The addons page still says the specific theme is enabled but it is not working.

**Comment by wagnerand** [comment]
Thank you for the report.

Could you please provide detailed steps to reproduce the problem?

Thank you.

**Comment by samuel1956** [comment]
I have had the same issue.  I have Firefox Quantum on a Windows 10 machine.  Whenever I start FF, it sometimes comes up with a blank or white background.  I go into Personas and choose the theme I want and have to double click it to make it work.  Then when I click on another tab, it goes back to white.
