### ISSUE TITLE
Apply this theme directly … not effective with Waterfox?

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/personas-plus#105]
At a glance: Personas Plus 1.8.3 https://addons.mozilla.org/addon/personas-plus/versions/?page=1#version-1.8.3 works as expected. 

With 2.0.1: each featured theme appears to be applicable, but clicking to apply has no effect. 

Workaround: click the 'Download and install from AMO' icon. 

Waterfox 56.2.1 on FreeBSD-CURRENT, 

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.53
$ date ; uname -v
Mon 18 Jun 2018 21:46:44 BST
FreeBSD 12.0-CURRENT #5 r335024: Wed Jun 13 11:04:24 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by wagnerand** [comment]
Thank you for the report!

I was able to reproduce this in Firefox 60 and fixed it in https://github.com/mozilla/personas-plus/commit/79121e9353a79a838a4f7b70d4fd4c7e55a2d3a0. I'll release a new version shortly.

**Comment by grahamperrin** [comment]
@wagnerand thanks but 2.0.2 seems to have the same issue (with Waterfox 56.2.2) …

**Comment by grahamperrin** [comment]
For reference only

The Classic Add-ons Archive URL: 

- caa:addon/personas-plus
