### ISSUE TITLE
Weird domain name

### ISSUE THREAD

**Issue by mvrhov** [mozilla/personas-plus#106]
As already commented in the commit /mozilla/personas-plus/79121e9353a79a838a by @Croydon. The weird domain name that appears in update the extension dialog is rather scary.
And IMO this looks like a bad practice coming from official mozilla extension.

**Comment by wagnerand** [comment]
There is currently no other way (that I know of) to make Personas Plus work. The domain name is our CDN for AMO static content.

**Comment by Croydon** [comment]
This should probably me mentioned somewhere on the AMO page (imho).

79121e9353a79a838a

**Comment by wagnerand** [comment]
Done.
