### ISSUE TITLE
PP does not load header image

### ISSUE THREAD

**Issue by cellarir** [mozilla/personas-plus#107]
I have used PP with a custom theme in FireFox for years.  Even with the new Quantum FF (ver 61), the custom theme I created and saved is still displayed, but I cannot find it in the custom or installed themes lists  - or even in the FF profile folder in  Users >...>mozilla > firefox.  When I try to create a new custom theme in either Firefox or Waterfox, when I browse to a 3000x200 px file for the header image, and click on it, it does not appear to be loaded and I can never "Set" the theme or even cancel out of the custom theme creation window.  Is the anyway to create new custom themes in PP?  Why does my old theme appear in FF but is not listed?

**Comment by cellarir** [comment]
I got it to work on one computer.   What is confusing is that I used to be able to identify the code by name in the profile folder, but it’s not there anymore.  I can’t even name the custom theme.

**Comment by wagnerand** [comment]
Yes, it's stored differently now, since the new architecture doesn't have access to the filesystem.
