### ISSUE TITLE
Can't find the settings button in Thunderbird 60

### ISSUE THREAD

**Issue by DandelionSprout** [mozilla/personas-plus#108]
I'm having substantial issues with this extension after I updated from Thunderbird 52 to Thunderbird 60.

In TB 52 there was a settings button for Personas Plus on the bottom bar, but in TB 60 it's mysteriously gone, meaning that I can't change themes. Would that be possible for you guys to fix?

**Comment by jvillalobos** [comment]
This extension is being discontinued shortly, given that lightweight themes are being phased out of Firefox in order to support a new kind of theme. Thunderbird will either need to fork this extension or come up with a different solution for it.
