### ISSUE TITLE
AMO login is working after a restart only

### ISSUE THREAD

**Issue by wagnerand** [mozilla/personas-plus#20]
Last time I looked into this, I think I saw the cookies-changed listeners not being set/enabled. I might be wrong though.

Adding @derinb.

**Comment by derinb** [comment]
Kris had disabled it. I enabled it in the file I sent with the email last week.

Then saw the commit and did not enable cookie-changed  observer for this commit. 

Kris' commit:
https://github.com/mozilla/personas-plus/commit/1c73888c9d069a527ac7741029f99acb736b49e2

I will keep it disabled for a while. If during tests, I come with login issue, I will enable it.

But if enabled, cookie-changed and http-on-modify-request may conflict with each other, though. If both enabled, they both try to retrieve favorites.json from AMO. So it requires extended testing.

**Comment by wagnerand** [comment]
I'm fine with using keeping `cookie-changed` disabled if we find another working method.

**Comment by wagnerand** [comment]
STR:

1. Install Personas Plus.
2. Restart (or not if you are using the restartless version)
3. Click on the PP icon -> "My Favorites" -> "Sign in ..."
4. Sign in into AMO.
5. Repeat step 3.

**Comment by derinb** [comment]
I am logging fine here. How many favorites do you have? I just have only 1 theme in my favorites. You might be hitting the [bug](https://github.com/mozilla/personas-plus/issues/22).

You might  want to 

1. create a dummy amo account
2. login
3. save only 1 or 2 themes as your favorites
4. log out
5. try to sign in by PP menu

It should go fine.

**Comment by wagnerand** [comment]
I only have two themes in my favorites list.

Are you sure you are using a clean working directory and `master` branch
while trying?

Can you reproduce with the current release version?

**Comment by derinb** [comment]
I have just tested both restartless and AMO version log-ins into my account without any issues.

Have you created a dummy account and tested?

**Comment by wagnerand** [comment]
Please try using my STR, especially do not log out.

**Comment by derinb** [comment]
1.     Install Personas Plus.
2.     Restart (or not if you are using the restartless version)
3.     Click on the PP icon -> "My Favorites" -> "Sign in ..."
4.     Sign in into AMO.
5.     Go back to step 3. The favorites is listed. There is no "Sign in" option because I am already logged in.

**Comment by derinb** [comment]
There might be an issue with your account. Have you made sure favorites.json is fetched correctly from AMO, you may want to use Network console. Also you may want to check personas folder in Profile folder.

Is there any errors on Console?

**Comment by wagnerand** [comment]
I can still reproduce using my mentioned steps. I suspect you're testing slightly different.
favorites.json is not fetched from AMO because the PP code does not even run after I have logged in (it does run when I log out). PP tries to download it during login (but before the AMO cookie is set) and therefore the XHR gets a redirect to the login page.

It does work in general though, for example when PP tries to fetch the json file while to cookie is already there.

**Comment by derinb** [comment]
Have you tested with the XPI file that force enables **cookie-changed** observer?

[Personas.Plus.Fix.Version.xpi.zip](https://github.com/mozilla/personas-plus/files/300958/Personas.Plus.Fix.Version.xpi.zip)

**Comment by wagnerand** [comment]
I am using authentication with Firefox Accounts.

Am Montag, 6. Juni 2016 schrieb derinb :

**Comment by derinb** [comment]
I see. I have been using older system. I will test with Firefox accounts.

I have enabled cookie-changed for the latest PR. It seems to be working fine.
