### ISSUE TITLE
 My Favorites menu doesn't always list favorites when signed in

### ISSUE THREAD

**Issue by derinb** [mozilla/personas-plus#22]
This should be handled urgently.

Most of the login issues are actually caused of this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=920557

**Comment by wagnerand** [comment]
That bug says it's a server issue?

**Comment by derinb** [comment]
Yes but users try to login via Personas Plus and when they fail they blame PP, understandably. Users do not have the server side technical knowledge. Most of the login issue reviews are because of this favorites bug. As long as this server side bug stays, they will try to complain about PP.

The issue should be fixed by AMO side but we should also help and track the progress here. If resolved, Personas Plus code may need to updated.

**Comment by derinb** [comment]
Andreas, that bugzilla bug is flagged as graveyard. Does it mean it needs to be re-submitted for new AMO?

**Comment by wagnerand** [comment]
Not necessarily. But we might need to ping someone about it.

**Comment by derinb** [comment]
[Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=920557) still in **graveyard**. Should I change **Product** to **addons.mozilla.org**?

**Comment by wagnerand** [comment]
No. The product `addons.mozilla.org` is for security bugs only. If you want to, you can clone the bug to github: https://github.com/mozilla/addons/issues/new

**Comment by derinb** [comment]
Related addons [issue](https://github.com/mozilla/addons/issues/160)
