### ISSUE TITLE
Follow-up of restartless changes

### ISSUE THREAD

**Issue by wagnerand** [mozilla/personas-plus#27]
https://github.com/mozilla/personas-plus/blob/c76df2863301d25f6140f67d86f3364ff78b7efc/extension/modules/personas.js#L1250

`PersonaController.SEAMONKEY_ID` does not exist.

https://github.com/mozilla/personas-plus/blob/c76df2863301d25f6140f67d86f3364ff78b7efc/extension/modules/personas.js#L1272

What app is `{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}`?
Please add a comment or better a constant.

**Comment by derinb** [comment]
It was there actually but I had to remove it because GUID were described it in PersonasService.

It is PaleMoon GUID. Does not hurt to stay there. But I can remove it.

**Comment by derinb** [comment]
I am removing {8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4} if it is OK?

**Comment by wagnerand** [comment]
Sure.

**Comment by derinb** [comment]
I am also removing survey code?

**Comment by wagnerand** [comment]
Yeah, you can do that. Please keep it separate PRs, though. You can submit several PRs at once without waiting for the previous ones to be merged. Just make sure to base your branches off `master` and not one of the feature-branches.

**Comment by derinb** [comment]
You can close this issue I suppose.
