### ISSUE TITLE
Reinstalling the Personas Plus add-on will cause display issues in the menu

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/personas-plus#38]
Steps to reproduce:

1.Install the Personas Plus version 1.8.0b1 add-on
2.Verify the add-on menu
3.Uninstall the add-on then install it again.

Expected results:
The add-on menu is displayed without any issues.

Actual results:
The add-on menu is displayed with issues.

Note/Issues:
Verified on FF48.0b7(Win 7 64-bit)
This issue is reproducing in AMO production server
This issue is reproducing with e10s enabled and disabled

Here is a video:
![menu](https://cloud.githubusercontent.com/assets/15885467/16870044/55158a00-4a88-11e6-9380-a8900ac4324c.gif)

**Comment by wagnerand** [comment]
Thanks for the report!

Adding @derinb.

**Comment by wagnerand** [comment]
We should fix this for 1.8.

**Comment by derinb** [comment]
This should be fixed by PR 44.
https://github.com/mozilla/personas-plus/pull/44

Because previous add-on was Restart, remnant of onQuitApplication caused issue for Restartless add-on.

Please test it on a fresh profile.

**Comment by cosminbadescuSV** [comment]
I tried with 1.8.0b3. here are the results:
-1.8.0b3. e10s enabled:
![menue10senabled](https://cloud.githubusercontent.com/assets/15885467/16909930/33034fb2-4cde-11e6-831a-75546792f962.gif)


-1.8.0b3. e10s disabled:
![menue10sdisabled](https://cloud.githubusercontent.com/assets/15885467/16910075/173ad40c-4cdf-11e6-9505-9bd89ec56c4a.gif)

**Comment by wagnerand** [comment]
Looks like this is working fine now. Thank you!
