### ISSUE TITLE
Restart is required after first install

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/personas-plus#41]
Steps to reproduce:

1.Install the Personas Plus version 1.8.0b1 add-on

Expected results:
No restart is required.

Actual results:
A restart is required.

Note/Issues:
Verified on FF48.0b7(Win 7 64-bit)
This issue is reproducing intermittently in AMO production server

Here is a video:
![restart](https://cloud.githubusercontent.com/assets/15885467/16872741/5f5256b0-4a97-11e6-815f-f19ab21a746f.gif)

**Comment by wagnerand** [comment]
Is this with e10s enabled?

**Comment by cosminbadescuSV** [comment]
The e10s was not enabled

**Comment by wagnerand** [comment]
Thanks.

Adding @derinb. Can you look into that, please? It blocks the release of 1.8. Thanks!

**Comment by wagnerand** [comment]
@cosminbadescuSV I wonder whether there is anything special about your installation there. I have seen screencasts for other bugs here where it is installed without showing the 'needs a restart' doorhanger.

**Comment by cosminbadescuSV** [comment]
This issue is reproducing only at first install on a new profile.

**Comment by derinb** [comment]
Cant produce it on my side.

You may have configuration issues on your local comp. Could you please try in another profile or another computer, if possible?

@wagnerand you can also be able to install on a fresh profile without restart, right?

**Comment by derinb** [comment]
Just a note, if you install Restartless version over AMO's current version of PP, it requires restart.

But on a fresh profile and for first install, it does not require Restart.

**Comment by cosminbadescuSV** [comment]
Installing PP on a new profile: http://screencast.com/t/tu1UupGL7FGm

**Comment by derinb** [comment]
I see. Really strange.

Could you please install local XPI file from your desktop?

BTW, you need to install **1.8.0b2** from the latest commit. 

Should @wagnerand compile for you?

**Comment by wagnerand** [comment]
This will be fixed in the next beta, as the milestone says.

@derinb are you going to fix more bugs before Monday? I don't want to create a beta for each patch. It's fine to fix a couple of them before releasing a new beta. The QA team can retest and close the bugs if they are fixed.

**Comment by wagnerand** [comment]
Wait, is https://github.com/mozilla/personas-plus/pull/44 supossed to fix this issue, @derinb?

**Comment by derinb** [comment]
Nope, 44 is for https://github.com/mozilla/personas-plus/issues/38

This is I think a configuration or AMO issue. Or maybe electrolysis flag in install.rdf may fix it.

I think you should compile XPI for them to test. electrolysis flag may fix this bug too, though my versions installs on Nightly Firefox without restart although I did not add electrolysis flag in install.rdf

**Comment by wagnerand** [comment]
How can this be an AMO issue? This has nothing to do with AMO.
As e10s was disabled during testing, it also has nothing to do with e10s.

Can you please give this another look and try to come up with a patch before I release a new beta? Thanks.

**Comment by derinb** [comment]
Andreas, `<em:bootstrap>true</em:bootstrap>` is already placed in `install.rdf`. There is nothing that may require add-on for Restart.

I am not sure about this issue and I can not produce the issue. That is why I recommended @cosminbadescuSV to test another computer.

**Comment by wagnerand** [comment]
I did some more digging.

@cosminbadescuSV In that profile, can you go to `about:support` and tell us what `Multiprocess Windows` shows?

**Comment by wagnerand** [comment]
I strongly suspect e10s was enabled afterall. I'm going to close this. Please try again in 1.8.0b3.

**Comment by cosminbadescuSV** [comment]
I tried with 1.8.0b3. here are the results:
-1.8.0b3. e10s enabled:
![restarte10senabled](https://cloud.githubusercontent.com/assets/15885467/16909214/d25dc286-4cd9-11e6-9199-cf36d5659f17.gif)

-1.8.0b3. e10s disabled:
![restarte10sdisabled](https://cloud.githubusercontent.com/assets/15885467/16909223/dec29bc8-4cd9-11e6-98ea-ac5bae3bb838.gif)

**Comment by wagnerand** [comment]
@cosminbadescuSV would you mind trying the same in aurora as well? If have been told that beta is a special case where we require add-ons to be on a special "allow list".

**Comment by cosminbadescuSV** [comment]
Of course :smile:  here are the videos:
-1.8.0b3. e10s enabled:
![restartaurorae10senabled](https://cloud.githubusercontent.com/assets/15885467/16913923/f325232a-4cf6-11e6-859d-635bcd1d5493.gif)


-1.8.0b3. e10s disabled:
![restartaurorae10sdisabled](https://cloud.githubusercontent.com/assets/15885467/16913926/f89bc5a2-4cf6-11e6-863f-8387dac33022.gif)

**Comment by wagnerand** [comment]
Looks good,thank you!
