### ISSUE TITLE
The list closes when hovering over a theme after removing the applied theme

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/personas-plus#42]
Steps to reproduce:

1.Install the Personas Plus version 1.8.0b1 add-on.
2.Go to about:addons and remove “Groovy Blue” theme.
3.Go to Personas Plus icon and hover over themes in “Featured”.

Expected results:
The list with themes is displayed without any issues.

Actual results:
The list closes after hovering over the themes.

Note/Issues:
Verified on FF48.0b7(Win 7 64-bit)
This issue is reproducing in AMO production server.
This issue is reproducing with e10s enabled and disabled

Here is a video:
![hover](https://cloud.githubusercontent.com/assets/15885467/16873902/c27d3ca8-4a9e-11e6-97d2-00e9d655b24a.gif)

**Comment by wagnerand** [comment]
@cosminbadescuSV For issues like this, can you please check the error log and see whether there is anything related to the add-on? Thanks!

**Comment by cosminbadescuSV** [comment]
This is what I receive in the browser console:
![hover2](https://cloud.githubusercontent.com/assets/15885467/16875696/681b3c78-4aa9-11e6-85bd-92ae88d64d17.gif)

**Comment by derinb** [comment]
Thanks for the report.

I think this bug is already available for current AMO version.

https://addons.mozilla.org/en-US/firefox/addon/personas-plus/

Could you install AMO  1.7.8 version on a new profile and follow same STR to produce the issue?

**Comment by cosminbadescuSV** [comment]
The issue is reproducing for 1.7.8 on a new profile, here are some videos:
![hover2](https://cloud.githubusercontent.com/assets/15885467/16878618/e269644e-4ab5-11e6-9fae-ce4df0a3f01c.gif)

![hover3](https://cloud.githubusercontent.com/assets/15885467/16878641/066d9450-4ab6-11e6-9f80-4d0d58768fe9.gif)

**Comment by derinb** [comment]
Yes this is Firefox bug. A new bugzilla bug needs to submitted for the issue.

Although it seems blocking, it does not seem to be an issue for production. I think no user reported a complaint about this bug in AMO reviews.

One way to fix is to install a new theme from Mozilla manually
https://addons.mozilla.org/en-US/firefox/addon/plush/

After that list works properly.

The issue is; Firefox does not like Theme change request if the current theme is Default. If there is an open menu or popup, theme change request closes the popup because LightWeightThemeManager adds some attributes to the navigation area and this modifies CSS and Popup settings. Therefore popup closes.

This issue not only closes PP menu. It also closes Pocket popup, too, if there a Theme change request is taking place.

**Comment by wagnerand** [comment]
Weird, I can't reproduce this on a fresh profile in Fx 47.0.1.

**Comment by derinb** [comment]
I can produce it on 47.0.1 Mac OS X.

**Comment by wagnerand** [comment]
Ah, I can reproduce it on Windows at least. @derinb you seem to know why this is happening. Could you file a bugzilla bug, please?

**Comment by derinb** [comment]
[Bugzilla report](https://bugzilla.mozilla.org/show_bug.cgi?id=1287158).

**Comment by derinb** [comment]
Workflow

In the case Default Theme is active and when hovered over Featured menu item, this workflow is executed

DOMMenuItemActive
https://github.com/mozilla/personas-plus/blob/1b395cee5aee9f02a6edc3740a22b66fb6dafae1/extension/content/personas.js#L1113

onPreviewPersona
https://github.com/mozilla/personas-plus/blob/1b395cee5aee9f02a6edc3740a22b66fb6dafae1/extension/content/personas.js#L710

 _previewPersona
https://github.com/mozilla/personas-plus/blob/1b395cee5aee9f02a6edc3740a22b66fb6dafae1/extension/content/personas.js#L749

previewPersona
https://github.com/mozilla/personas-plus/blob/1b395cee5aee9f02a6edc3740a22b66fb6dafae1/extension/modules/service.js#L1017

_notifyWindows(aData);
https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/LightweightThemeManager.jsm#222

lightweight-theme-styling-update
https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/LightweightThemeManager.jsm#798

lightweight-theme-styling-update observer
https://dxr.mozilla.org/mozilla-esr45/source/toolkit/modules/LightweightThemeConsumer.jsm#72

root.setAttribute("lwtheme", "true");
https://dxr.mozilla.org/mozilla-esr45/source/toolkit/modules/LightweightThemeConsumer.jsm#126

**Comment by derinb** [comment]
`root.setAttribute("lwtheme", "true");`

is the bug line. When setting **lwtheme** attribute to **true** for `window.document.documentElement`, which is root element of Firefox Window, open popups and theme are closed.

**Comment by wagnerand** [comment]
Great, thanks!
