### ISSUE TITLE
A custom persona can't be re enabled from about:addons 

### ISSUE THREAD

**Issue by madalincm** [mozilla/personas-plus#48]
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
Persona Plus version: 1.8.0b3
### Steps to reproduce:
1. Go to Tools - Personas - Custom Personas, create and apply a custom persona.
2. Install another theme.
3. Go to about:addons - appearance and click the enable button for the custom persona.
### Expected results:

The custom persona can be enabled from about:addons
### Actual results:

The custom persona can't be aenabled from about:addons
### Notes/Issues:

Issue can be reproduced in FF 47.0b7
### Screencast for this issue:

![custompersonaenable](https://cloud.githubusercontent.com/assets/15685441/16942556/4a24111a-4d9f-11e6-9b6f-adf65fa72e27.gif)

**Comment by wagnerand** [comment]
Not sure how easily fixable that is. That entry might or might not be just a dummy entry.

**Comment by derinb** [comment]
Did not test yet bug this seems to be a Firefox bug rather than add-on.

**Comment by derinb** [comment]
This seems to be an old Firefox bug. When **Enable** button is clicked, below console error is thrown:

`uncaught exception: 2147942487`

I did a quick search on [Google](https://www.google.com/?#q=uncaught+exception%3A+2147942487). Here are the most related bug reports:

https://groups.google.com/forum/#!topic/mozilla-labs-personas/GZvapdMQFQA
https://bugzilla.mozilla.org/show_bug.cgi?id=554220

A new bug may need to be submitted, though.

@wagnerand , you may want to consider removing this from 1.8.1 milestone.
