### ISSUE TITLE
Restarting the browser does not change the theme

### ISSUE THREAD

**Issue by madalincm** [mozilla/personas-plus#51]
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
Persona Plus version: 1.8.0b3
### Steps to reproduce:
1. Go to tools - Personas - Featured and click on Random Selection From Featured
2. Restart the browser
### Expected results:

If the Random Selection from Featured option is selected the theme is changing after restart.
### Actual results:

The theme is not changing. 
### Notes/Issues:

Issue can be reproduced in FF 47.0b7
### Screencast for this issue:

![restartpersonasplus](https://cloud.githubusercontent.com/assets/15685441/16950102/2bdc6040-4dc7-11e6-8d0b-f634669d8c5c.gif)

**Comment by wagnerand** [comment]
Hm, that's odd. @derinb do you have an idea what could be causing this and how easy it would be to fix it?

**Comment by derinb** [comment]
I think that menu option has always been Session only. It is present in [AMO version](https://addons.mozilla.org/en-US/firefox/addon/personas-plus/), too.

Probably if the theme is switched at start-up, user would complain because she might like the last theme in previous Session and having it go without notice may not be preferable. So previous developers probably did code the feature Session only.

Changing at start-up may turn that feature into Rotator feature. It was offered in survey but it did not get prioritization in survey results.

**Comment by wagnerand** [comment]
We should keep the persona that was selected last.

**Comment by madalincm** [comment]
If we want to keep the last selected persona then we should change the Add-on description. Please read the last paragraph here: https://addons.mozilla.org/en-US/firefox/addon/personas-plus/?src=search

If we don't want them to change we should not advertise that :)
What do you thing @wagnerand

**Comment by wagnerand** [comment]
Interesting, I did not know about the rotating feature if you select a persona from the "random" category. Wouldn't that be a better fit for the _Rotater_ add-on?

**Comment by derinb** [comment]
Yes there is a rotator feature but it was broken for years. I think it was disabled intentionally because of a serious bug in very older version of Firefox.

**Comment by derinb** [comment]
I edited AMO page to by removing rotation statement:

>  If you select, for example, "Random Selection from Abstract" on the "Abstract" Personas menu, Personas Plus will randomly select a new theme from that list.

@wagnerand you may want to close this because rotation feature is not in survey results.

**Comment by wagnerand** [comment]
As far as I can see, this bug is still valid.

We either need to fix the rotation (and add the text back into the AMO page), or remove the rotation entirely (including on restart, which this bug is about).

**Comment by derinb** [comment]
But Amy and Jorge said they want to keep PP as simple and did not want to include rotation function. I offered them to include rotation feature. 

It was also because mine Personas Rotator add-on does the rotation job. But still Personas Rotator uses the APIs available in Personas Plus.

As a compromise, the rotation APIs should be there but as hidden, imho.

**Comment by wagnerand** [comment]
No more hidden features that are undocumented, half working and no one knows the code about or wants to work on.

**Comment by derinb** [comment]
But as I said, Amy and Jorge do not want the rotation feature. If the rotation API is removed, I need to almost duplicate all Personas Plus add-on code to get Personas Rotator add-on working again. This does not make sense for both sides.

I think Amy and Jorge should join the conversation.

**Comment by wagnerand** [comment]
If the rotation code is not used in PP, we should remove it. Feel free to move the entire code to your own add-on if the license you're using allows it.

**Comment by derinb** [comment]
Well Persona Rotator is a companion add-on for Personas Plus. Its UI is placed inside PP menu and it needs the Featured and Favorites list from PP.

Duplicating the add-on means calling Mozilla server for featured and favorites list again unnecessarily. Critical race conditions will happen. Even I had race conditions with restart version of Personas Plus.

I recommend keeping the rotating code in Personas Plus and exposing the API for external add-ons.

**Comment by wagnerand** [comment]
I am talking about https://github.com/mozilla/personas-plus/blob/master/extension/modules/service.js#L1123-L1145 and https://github.com/mozilla/personas-plus/blob/master/extension/modules/service.js#L1199-L1213 (and the timer). Sorry if that was not clear.

I had a look at your code and you are already overriding `_rotationTimer`, you might as well just create your own one. Note that the variable is prefixed by an underline which is generally known as "not designed to be used externally". This would make both PP and your add-on more robust as you don't have to rely on a time in another add-on.

Removing `_rotatePersona` (another _internal_ function) is not a big deal either, you could just copy and paste that whole function into your add-on and just replace `this`. Done.

**Comment by derinb** [comment]
OK good idea. But there is a need to create a Component in bootstrap.js of Personas Plus which should expose PersonaController as wrappedJSObject so that other add-ons can reach PersonaController API.

Do you have any other idea for exposing PersonaController?

**Comment by wagnerand** [comment]
What do you need `PersonaController` for?

**Comment by derinb** [comment]
Because `PersonaController` is added to `bootstrap.js,` I am planning to add methods and related properties for rotation in `PersonaController` so that other add-ons can use it.

**Comment by wagnerand** [comment]
So, that's out of the scope for this bug.
