### ISSUE TITLE
Options\Disable\Remove sections in about:addons looks broken after installing Personas Plus

### ISSUE THREAD

**Issue by vcarciu** [mozilla/personas-plus#52]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0 
FF : 48.0b7

Steps to reproduce:
1.Install latest Personas Plus from https://addons.mozilla.org/en-US/firefox/addon/personas-plus/#beta-channel
2.Go to about:addons and select Extensions tab
3.Observe the Options\Disable\Remove section for newly installed Personas Plus

Expected results:
All buttons are displayed without issues

Actual results:
The Options\Disable\Remove section looks broken
e10s disabled

NOTES:Working as expected after a refresh

Please see the photo for this issue below : 
![personasplus](https://cloud.githubusercontent.com/assets/1583842/16950645/01ebf338-4dca-11e6-9e9c-c8b61738e0ac.png)

**Comment by derinb** [comment]
This is a Firefox issue, imho. Happens for other restartless add-ons, too. 

About:addons page need to reloaded or another Tab like Get Add-ons should be clicked then back to Extensions tab fixes it.

**Comment by wagnerand** [comment]
Yeah, I think so. I'm going to talk to add-ons manager folks to confirm.

**Comment by wagnerand** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1288056
