### ISSUE TITLE
Unhandled promise

### ISSUE THREAD

**Issue by wagnerand** [mozilla/personas-plus#56]
```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Wed Jul 20 2016 15:15:10 GMT+0200 (CEST)
Full Message: Unix error 14 during operation remove (Bad address)
Full Stack: JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: PendingErrors.register :: line 195
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.completePromise :: line 718
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 973
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 816
```

I am not entirely sure how to find the source of this.

It happens sooner or later after installing the add-on. No interaction needed.

**Comment by derinb** [comment]
I think this is a Firefox issue I suppose. I seen this for others add-ons when they are installed.

**Comment by wagnerand** [comment]
Well, we need to find out.

Can you link to another add-on that shows the same error?

**Comment by derinb** [comment]
OK it seems because of `refreshFavorites`

https://github.com/mozilla/personas-plus/blob/bdc9b9b92d973510a3145eda4f11c39f05e5ca1b/extension/modules/service.js#L433

**Comment by wagnerand** [comment]
That makes sense. I've seen this when network requests to the previews happened. Thanks for figuring this out. Can you submit a PR, please?

**Comment by derinb** [comment]
Exact line is [OS.File.remove(path.spec);](https://github.com/mozilla/personas-plus/blob/bdc9b9b92d973510a3145eda4f11c39f05e5ca1b/extension/modules/service.js#L618)

Not sure why the favorites.json is tried to being removed?

**Comment by wagnerand** [comment]
I **assume** it's being removed, because we don't have a valid set of featured add-ons at that point and we want to prevent others from reading that json file, which in fact is not json. And that would cause JSON parsers to fail...

**Comment by derinb** [comment]
I think it is because there is no check for favorites.json existence. If user did not login AMO, then there is no favorites.json. But PP is trying to remove non-existence file and this creates a Promise error.

A simple exists check should fix it, I suppose.

**Comment by derinb** [comment]
[PR 57](https://github.com/mozilla/personas-plus/pull/57)
