### ISSUE TITLE
 Theme info bar cannot be dismissed by clicking the "Undo" button after uninstalling Persona Plus

### ISSUE THREAD

**Issue by wagnerand** [mozilla/personas-plus#82]
Clones from https://bugzilla.mozilla.org/show_bug.cgi?id=1313673:

Steps to reproduce:
1. Install attached "Persona Plus" add-on from about:addons
2. Remove the "Persona Plus"
3. Click the "Undo" button from the info bar

Expected results:
The info bar is dismissed.

Actual results:
Nothing happens.

Notes/Issues:
Reproducing also if add-on is disabled.
Verified on FF49.0.2 using Windows 7 x64
Screencast for this issue: http://screencast.com/t/0SsFZnIVdrMj

/cc @ValentinaPC

**Comment by ValentinaPC** [comment]
@wagnerand : Where (or how) can I check this to see it is fixed? Thanks!

**Comment by wagnerand** [comment]
@ValentinaPC Do the STR above not work for you?

**Comment by ValentinaPC** [comment]
Well, of course they do - I wrote them - but still happening the same - "undo" option is not dismissed. :smile:

**Comment by wagnerand** [comment]
Oh, ok! 😄 

@derinb Can you check this and/or update the STR please?

**Comment by derinb** [comment]
@wagnerand I think you should compile the latest XPI for Valentina. She is probably testing with the old XPI file.

@ValentinaPC Please let us know if you have the latest XPI from the latest commit.

Thanks

**Comment by ValentinaPC** [comment]
@derinb : I think I don't, but I'd love to have it. :smile:

**Comment by wagnerand** [comment]
Ah yes, sorry I didn't think about that.

@ValentinaPC I just uploaded a new beta version: https://addons.mozilla.org/en-US/firefox/addon/personas-plus/

**Comment by wagnerand** [comment]
Awesome, thank you!
