### ISSUE TITLE
PERSONAS PLUS NOT WORKING CORRECTLY

### ISSUE THREAD

**Issue by MaDonnasPersonas** [mozilla/personas-plus#86]
I was told to post on here about the problem with PP. I have posted it so many places but will do so here. As of today, PP is not letting me check my themes by using the fox icon/Personas/Custom/Edit. Nothing happens when I try. I noticed an update of the program this morning on my Add Ons. I was asked to submit the Browser Console so I am trying to do so. I don't know anything about doing this so if this isn't what is needed, I don't know. 

![capture](https://cloud.githubusercontent.com/assets/17728178/20547116/d7c2bf48-b0ce-11e6-8c13-748558e62571.JPG)

I am just an old lady that makes Persona themes so when it comes to programming, etc. I am no help. Sorry about that. 

MaDonna

**Comment by wagnerand** [comment]
Thank you for the report, almost there. Can you please click inside the browser console, press CTRL+A, then CTRL+C and paste the content into this issue?

Also, can you please provide detailed steps how to reproduce the issue?

Thank you.

**Comment by MaDonnasPersonas** [comment]
ignotifier:111 sandbox.js:340
Warning: ‘nsIOService::NewChannel()’ deprecated, please use
‘nsIOService::NewChannel2()’ script-compiler.js:21:13
TypeError: prefs.getIntPref is not a function[Learn More]  overlay.js:23:18
Empty string passed to getElementById().
rs=AHGWq9A2PASyC80Al4phlyygjsi4t2fy_g:404:341

CTRL C

**Comment by MaDonnasPersonas** [comment]
CTR; A

ignotifier:111  sandbox.js:340
Empty string passed to getElementById().  rs=AHGWq9A2PASyC80Al4phlyygjsi4t2
fy_g:404:341
Use of Mutation Events is deprecated. Use MutationObserver instead.  rs=
AHGWq9A2PASyC80Al4phlyygjsi4t2fy_g:126:398
Warning: ‘nsIOService::NewChannel()’ deprecated, please use
‘nsIOService::NewChannel2()’  script-compiler.js:21:13
Empty string passed to getElementById().  rs=AHGWq9A2PASyC80Al4phlyygjsi4t2
fy_g:404:341
Empty string passed to getElementById().  rs=AHGWq9A2PASyC80Al4phlyygjsi4t2
fy_g:404:341
https://mail.google.com/mail/u/0/#inbox : Unable to run script because
scripts are blocked internally.  (unknown)
https://mail.google.com/mail/u/0/#inbox/1588e9a938fab622 : Unable to run
script because scripts are blocked internally.  (unknown)
https://mail.google.com/mail/u/0/#inbox : Unable to run script because
scripts are blocked internally.  (unknown)
https://mail.google.com/mail/u/0/#inbox/1588e9a938fab622 : Unable to run
script because scripts are blocked internally.  (unknown)
https://mail.google.com/mail/u/0/#inbox : Unable to run script because
scripts are blocked internally.  (unknown)
https://mail.google.com/mail/u/0/#inbox/1588e9a938fab622 : Unable to run
script because scripts are blocked internally.  (unknown)
Empty string passed to getElementById().  rs=AHGWq9A2PASyC80Al4phlyygjsi4t2
fy_g:404:341
Empty string passed to getElementById().  rs=AHGWq9A2PASyC80Al4phlyygjsi4t2
fy_g:404:341
Empty string passed to getElementById().  rs=AHGWq9A2PASyC80Al4phlyygjsi4t2
fy_g:404:341
Warning: ‘nsIOService::NewChannel()’ deprecated, please use
‘nsIOService::NewChannel2()’  script-compiler.js:21:13
Empty string passed to getElementById().  rs=AHGWq9A2PASyC80Al4phlyygjsi4t2
fy_g:404:341


CTRL C

Empty string passed to getElementById().
rs=AHGWq9A2PASyC80Al4phlyygjsi4t2fy_g:404:341
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please
use directive ‘child-src’ instead. (unknown)
TypeError: prefs.getIntPref is not a function[Learn More]  overlay.js:23:18
Warning: ‘nsIOService::NewChannel()’ deprecated, please use
‘nsIOService::NewChannel2()’ script-compiler.js:21:13
Warning: ‘nsIOService::NewChannel()’ deprecated, please use
‘nsIOService::NewChannel2()’ script-compiler.js:21:13
TypeError: prefs.getIntPref is not a function[Learn More]  overlay.js:23:18
Warning: ‘nsIOService::NewChannel()’ deprecated, please use
‘nsIOService::NewChannel2()’ script-compiler.js:21:13
Warning: ‘nsIOService::NewChannel()’ deprecated, please use
‘nsIOService::NewChannel2()’ script-compiler.js:21:13
Use of Mutation Events is deprecated. Use MutationObserver instead.

I hope this is what you wanted.

If this wasn't how I was supposed to do it, etc. please let me know.
Because I don't know if I did it right or not.

**Comment by MaDonnasPersonas** [comment]
![2](https://cloud.githubusercontent.com/assets/17728178/20548745/feffac54-b0da-11e6-98ab-a2d76f5556a3.JPG)

**Comment by MaDonnasPersonas** [comment]
The first screen shot is where I test a theme design, but when I click on
Browse to check the theme Header, the header design I made should show up,
but nothing happens. The same with Footer.

**Comment by wagnerand** [comment]
Thanks you, the last screenshot gives us a hint.

@derinb can you please look into that error?

**Comment by derinb** [comment]
@wagnerand Andreas, please release this version asap after accepting PR so that MaDonna and other users can use it. I will handle other Nightly issues later.

@MaDonnasPersonas Thanks MaDonna for the information and feedback. The issue will be solved for the upcoming version.

**Comment by MaDonnasPersonas** [comment]
Thanks so much for the quick fix.

**Comment by MaDonnasPersonas** [comment]
Can you please notify us when the new "fixed" version is out?

**Comment by wagnerand** [comment]
A new version containing this fix has just been pushed to AMO and should be reviewed shortly.

**Comment by MaDonnasPersonas** [comment]
Thanks so much.
