### ISSUE TITLE
Footer Image Size is 3000px 100px

### ISSUE THREAD

**Issue by derinb** [mozilla/personas-plus#88]
Specification page requires images to be 3000px wide and **200px** long.

https://developer.mozilla.org/en-US/Add-ons/Themes/Lightweight_themes

But Groovy Blue footer image is 3000px **100px**

I tried another AMO persona and saw its length is **100px**

AMO persona footer image length and specification page length conflicts.

**Comment by wagnerand** [comment]
I don't see how this is a PP bug.
Regardless, as Firefox does not use the footer anymore I assume the requirements are about the header dimensions only.

**Comment by derinb** [comment]
I got the footer image of Groovy Blue theme from Profile folder > personas > cache

It is 3000x100.

If I load that 3000x100 image into the Footer section of Custom Persona page, it warns as it must be 3000x200 and directs uses to the tutorial page.

So either footer dimension needs to be updated in add-on properly or in AMO tutorial. But AMO personas will still have the 3000x100 footer images though.

**Comment by wagnerand** [comment]
Ah. Probably best to distinguish between header and footer image in PP then.

**Comment by derinb** [comment]
But tutorial must also mention about that. There is no dimension value for Footer in AMO tutorial.

**Comment by wagnerand** [comment]
The tutorial is Firefox-oriented, and Firefox does not have a footer to style anymore.

**Comment by wagnerand** [comment]
But of course, you can add a note for other products on that page, although it's best to verify first what the actual requirements for other products are...

**Comment by derinb** [comment]
OK let me remove footer image dimension check then. It is not cross application so there is no need to check its dimensions?
