### ISSUE TITLE
Disabling Image Size Restriction

### ISSUE THREAD

**Issue by derinb** [mozilla/personas-plus#94]
Some users do not create themes for AMO submission and want to casually test images for the browsers.

https://addons.mozilla.org/en-US/firefox/addon/personas-plus/reviews/837053/

Disabling the restriction by a preference or even with a preference that can only be accessible via about:config may help for those kind of users.

If it is acceptable, I like to add the preference.

**Comment by wagnerand** [comment]
A preference for that seems reasonable, but I think it should be disabled by default.

Loading images with unsupported resolutions might result in weird effects and we should be clear that this is not supported.

**Comment by derinb** [comment]
Sure it will be set to disabled as default to comply AMO.

Is showing a warning prompt necessary when the preference is enabled? Users are already prompted by Image Size prompt, though.

**Comment by wagnerand** [comment]
I don't think showing a warning prompt is necessary.
