### ISSUE TITLE
Image restrictions not fixed

### ISSUE THREAD

**Issue by Moltresrider** [mozilla/personas-plus#96]
The image restrictions fix that is said to be fixed on the addon indeed not fixed. There is a mention that it was put into the addon but I downloaded the latest version from addons.mozilla.org but there is no option to use my old theme that is not the size it wants. it still tells me that it doesn't meet the requirements and the only option in preferences is to show preview when selecting from the menu. I see that that bug was handled in January and it is now May and this disable image dimensions restriction fix is NOT on the latest version. Still no option to allow any image sizes despite it shows up as fixed. My theme still does not work because of this and I cannot get it on my Firefox because the option in preferences is non-existent.

**Comment by wagnerand** [comment]
Issues are marked as fixed when the code-change lands, not when a new version has been approved. That being said, I try to release a new version this week.

**Comment by Moltresrider** [comment]
It has been over a week and still no option! You need to reopen this bug because there is still no option even 9 days later, more than a week
