### ISSUE TITLE
1.8.3 still not working

### ISSUE THREAD

**Issue by Moltresrider** [mozilla/personas-plus#98]
According to this page and about:addons, the app has been updated as of May 20, 2016, a week and a half after my original bug report on this issue, but after it updated, the option to disable image restrictions is still not present and I still cannot apply my theme.

The update does not fix the issue at all

**Comment by wagnerand** [comment]
Please provide steps to reproduce the issue you are experiencing.

**Comment by Moltresrider** [comment]
Click the Firefox Personas icon,
click 'Preferences'
in there, there is no "disable image restrictions" option

attempt to load a 1366x150 image into the header and a 1366x100 as the footer (The best image for my display), error "The image you selected does not meet the requirements. images must be 3000x300"

**Comment by Moltresrider** [comment]
![problem 3](https://cloud.githubusercontent.com/assets/15950951/26463768/6dfc66fc-4153-11e7-978a-a347a285c8ab.jpg)
![problem](https://cloud.githubusercontent.com/assets/15950951/26463770/6e007756-4153-11e7-9739-8d793a03d031.jpg)
![problem 2](https://cloud.githubusercontent.com/assets/15950951/26463769/6dfd123c-4153-11e7-8d79-92bafcd6972c.jpg)


Screenshots

**Comment by wagnerand** [comment]
There is no preference for this in the Personas Plus UI. You can flip the preference `extensions.personas.restrictDimensions` manually using about:config.
