### ISSUE TITLE
WebExtension 

### ISSUE THREAD

**Issue by Croydon** [mozilla/personas-plus#99]
I have found in some BugZilla issues notes that this add-on might be ported.

Could you provide information if this is actually the case?

**Comment by wagnerand** [comment]
Yes, we are working on it.

**Comment by Croydon** [comment]
@wagnerand Any more information you could provide? Is there already some alpha/beta version? A rough time table?

**Comment by wagnerand** [comment]
There is a rough prototype which I wouldn't want recommending anyone to use. The UI is far from being usable, I just need something to test WebExtensions APIs and AMO integration.

The tentative (!) plan is to have a (beta) version to share in October and have a final release before 57 gets released.
